import type { ChecklistItem, Grave, RepoSignals, RevivalDifficulty, RevivalPlan } from "./types";

/**
 * Turn a grave + its health signals into a concrete, Copilot-ready revival plan:
 * a diagnosis, a prioritized checklist, a tailored copilot-instructions.md, and
 * copy-paste Copilot prompts.
 */
export function buildRevivalPlan(grave: Grave, signals: RepoSignals): RevivalPlan {
  const repo = grave.repo;
  const lang = repo.language || "the project";
  const diagnosis: string[] = [];
  const checklist: ChecklistItem[] = [];
  const prompts: string[] = [];

  // The thing that actually makes you quit: you forgot what it did. Always first.
  prompts.push(
    `I abandoned my ${lang} project "${repo.name}" ${grave.daysCold.toLocaleString(
      "en-US"
    )} days ago and forgot how it works. Read the codebase and explain its architecture, entry points, and which parts look half-finished — in plain language.`
  );
  checklist.push({ task: "Re-read the code and note where you left off", priority: 0 });

  if (!signals.hasReadme) {
    diagnosis.push("No README — future-you has no way back in.");
    checklist.push({ task: "Write a README (what / why / how to run)", priority: 1 });
    prompts.push(
      `Write a README.md for my ${lang} project "${repo.name}". Cover what it does, why it exists, install steps, and a 30-second quickstart. Current description: "${
        repo.description || "none"
      }".`
    );
  }
  if (!signals.hasTests) {
    diagnosis.push("No tests — every change is a leap of faith.");
    checklist.push({ task: "Add a test harness + one smoke test", priority: 2 });
    prompts.push(
      `Set up a test harness for this ${lang} project and write one smoke test that exercises the core entry point of "${repo.name}".`
    );
  }
  if (!signals.hasLicense) {
    diagnosis.push("No license — legally, nobody can use it.");
    checklist.push({ task: "Add a LICENSE (MIT is a safe default)", priority: 3 });
    prompts.push(`Add an MIT LICENSE file for "${repo.name}" and reference it from the README.`);
  }
  if (!signals.hasCI) {
    diagnosis.push("No CI — nothing catches a broken commit.");
    checklist.push({ task: "Add a GitHub Actions CI workflow", priority: 4 });
    prompts.push(
      `Create a GitHub Actions workflow at .github/workflows/ci.yml that installs dependencies and runs the build and tests for this ${lang} project on push and pull_request.`
    );
  }
  if (signals.openIssues > 0) {
    const n = signals.openIssues;
    diagnosis.push(`${n} open issue${n === 1 ? "" : "s"} left hanging.`);
    checklist.push({ task: `Triage the ${n} open issues into a v1 milestone`, priority: 5 });
    prompts.push(
      `Review the ${n} open issues on "${repo.name}", group them into themes, and propose a single "v1" milestone containing the 3 highest-impact ones.`
    );
  }

  if (diagnosis.length === 0) {
    diagnosis.push("Honestly? It's in decent shape. It just needs you to show up again.");
  }

  checklist.sort((a, b) => a.priority - b.priority);

  const gaps = [signals.hasReadme, signals.hasTests, signals.hasLicense, signals.hasCI].filter(
    (x) => !x
  ).length;
  const difficulty: RevivalDifficulty =
    grave.daysCold > 730 || gaps >= 4
      ? "ancient-burial"
      : grave.daysCold > 365 || gaps >= 2
        ? "six-feet-under"
        : "shallow-grave";

  const estimatedSessions = Math.max(1, Math.ceil(checklist.length / 2));

  return {
    repoName: repo.name,
    diagnosis,
    checklist,
    difficulty,
    estimatedSessions,
    copilotInstructions: renderCopilotInstructions(grave, signals),
    prompts,
  };
}

/** A tailored .github/copilot-instructions.md body that steers Copilot for the revival. */
export function renderCopilotInstructions(grave: Grave, signals: RepoSignals): string {
  const repo = grave.repo;
  const lang = repo.language || "Unknown";
  const wants: string[] = [];
  if (!signals.hasReadme) wants.push("- A clear README is missing; explain code as if onboarding a newcomer.");
  if (!signals.hasTests) wants.push("- There are no tests; propose tests alongside any new code.");
  if (!signals.hasCI) wants.push("- There is no CI; prefer changes that are easy to verify in CI.");
  if (signals.openIssues > 0) wants.push(`- ${repo.open_issues_count} issues are open; tie changes back to them where relevant.`);

  return `# Copilot instructions — ${repo.name}

> Generated by Lazarus to help revive a project abandoned ${grave.daysCold.toLocaleString(
    "en-US"
  )} days ago.

## Project
- **Name:** ${repo.name}
- **Primary language:** ${lang}
- **What it is:** ${repo.description || "TODO: describe the project in one line."}
- **Status:** Being revived after ~${Math.round(grave.daysCold / 30)} months dormant. Diagnosed cause of death: ${grave.causeOfDeath}.

## How to help me
- Assume I have forgotten the internals. Prefer small, well-explained changes over large rewrites.
- Match the existing ${lang} style and structure already in the repo. Do not restructure unprompted.
- When I ask for a feature, first restate what the existing code does, then propose the change.
${wants.length ? `\n## Known gaps to close\n${wants.join("\n")}` : ""}

## Definition of "finished" for this revival
- Runs from a clean clone with documented steps.
- Has at least one test and a green CI run.
- Has a README a stranger could follow.
`;
}
